name: Post artifact link
on:
  workflow_dispatch:
  workflow_run:
    workflows: ["build"]
    types:
      - "completed"

jobs:
  post-artifacts:
    runs-on: ubuntu-latest
    steps:
      # exposes urls of found artifacts as env vars, if their name contains "release-build"
      - name: Expose artifacts to env
        id: new
        uses: "michpohl/expose-artifacts@v1.0.0"
        with:
          github-token: "${{ secrets.GITHUB_TOKEN }}"
          output-var-name: "RELEASE_ARTIFACT"
          contains-string: "release-build"
      - name: Use env var
        run: |
          echo $RELEASE_ARTIFACT
          echo $RELEASE_ARTIFACT_0
