name: "Upload SARIF"

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - README.md
  workflow_call:

jobs:
  build:
    #runs-on: self-hosted #ubuntu --- con PVS-Studio installato
    runs-on: ubuntu-latest
    steps:
    # This step checks out a copy of your repository.
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: run 
      run: |
        pip install anybadge     
        anybadge --label=test --value=default --file=badge.svg
        ls -la

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: release-build
        path: badge.svg
    - uses: wow-actions/add-badges@v1
      env:
        repo_url: ${{ github.event.repository.html_url }}
        repo_name: ${{ github.event.repository.name }}
        repo_owner: ${{ github.event.repository.owner.login }}
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        badges: "-f badge.svg"
