name: "Upload SARIF"

on:
  push:
  workflow_call:

jobs:
  build:
    #runs-on: self-hosted #ubuntu --- con PVS-Studio installato
    runs-on: ubuntu-latest
    steps:
    # This step checks out a copy of your repository.
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: run 
      run: |
        pip install anybadge     
        anybadge --label=test --value=default --file=badge.svg
    
    - name: badge
      uses: wow-actions/add-badges@v1
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        badges: |
          {
            "badge": "https://img.shields.io/github/license/${{ env.repo_owner }}/${{ env.repo_name }}?style=flat-square,
            "alt": "Project badge",
            "link": "https://eclairit.com:3787/fs/home/emelin/github/$GITHUB_REPOSITORY/last_main/PROJECT.ecd"
          }
          
        
        # Opening comment
        #opening_comment: # optional, default is <!-- [START BADGES] -->
        # Closing comment
        #closing_comment: # optional, default is <!-- [END BADGES] -->
