name: "Upload SARIF"

on:
  workflow_dispatch:
  push:
    paths-ignore:
      - README.md
  workflow_call:

jobs:
  build:
    #runs-on: self-hosted #ubuntu --- con PVS-Studio installato
    runs-on: ubuntu-latest
    steps:
    # This step checks out a copy of your repository.
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: run 
      run: |
        pip install anybadge     
        anybadge --label=test --value=default --file=badge.xml
        ls -la

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: release-build
        path: badge.svg
    - name: OpenCover Badge Generator
      uses: danpetitt/open-cover-badge-generator-action@v1.0.9
      with:
        path-to-opencover-xml: badge.xml
        path-to-badges: ./
        minimum-coverage: 75
        repo-token: ${{ secrets.GITHUB_TOKEN }}
