name: "Upload SARIF"

on:
  push:
  workflow_call:

jobs:
  build:
    #runs-on: self-hosted #ubuntu --- con PVS-Studio installato
    runs-on: ubuntu-latest
    steps:
    # This step checks out a copy of your repository.
    - name: Checkout repository
      uses: actions/checkout@v2
      
    - name: run 
      run: |
        pip install anybadge     
        anybadge --label=test --value=default --file=badge.svg

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: release-build
        path: badge.svg

    - name: Expose artifacts to env
      uses: "michpohl/expose-artifacts@v1.0.0"
      with:
        github-token: "${{ secrets.GITHUB_TOKEN }}"
        output-var-name: "RELEASE_ARTIFACT"
        contains-string: "release-build"
    - name: Use env var
      run: |
        echo $RELEASE_ARTIFACT
