name: "Upload SARIF"

on: 
  workflow_dispatch:

jobs:
  job1:
    runs-on: Windows
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: prima parte
      run: |
        echo "prima parte"
  job2:
    runs-on: self-hosted
    steps:
    - name: seconda parte
      run: |
        echo "seconda parte"
      
