name: "PVS su Windows"

on: 
  workflow_dispatch:

jobs:    
  job2:
    runs-on: self-hosted
    steps:
    - name: seconda parte
      run: |
        gcc -W f.c
        CLMonitor.exe analyze -l PVS-Studio.lic -o ris.plog
        plogConverter.exe ris.plog -t sarif -n results
